{{- if .Values.tokenServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sebastian.fullname" . }}-token-server
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
    {{- include "sebastian.selectorLabels" (dict "ctx" . "component" "token-server") | nindent 4 }}
  {{- with .Values.tokenServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tokenServer.service.port }}
      targetPort: {{ .Values.tokenServer.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "sebastian.selectorLabels" (dict "ctx" . "component" "token-server") | nindent 4 }}
{{- end }}
