/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstallerRouteImport } from './routes/installer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesIndexRouteImport } from './routes/devices.index'
import { Route as RecordingsRecordingIdRouteImport } from './routes/recordings.$recordingId'
import { Route as InstallerControlRoomDotjsonRouteImport } from './routes/installer.control-room[.]json'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices.$deviceId'

const InstallerRoute = InstallerRouteImport.update({
  id: '/installer',
  path: '/installer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRecordingIdRoute = RecordingsRecordingIdRouteImport.update({
  id: '/recordings/$recordingId',
  path: '/recordings/$recordingId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallerControlRoomDotjsonRoute =
  InstallerControlRoomDotjsonRouteImport.update({
    id: '/control-room.json',
    path: '/control-room.json',
    getParentRoute: () => InstallerRoute,
  } as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => DevicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/installer': typeof InstallerRouteWithChildren
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/installer/control-room.json': typeof InstallerControlRoomDotjsonRoute
  '/recordings/$recordingId': typeof RecordingsRecordingIdRoute
  '/devices/': typeof DevicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/installer': typeof InstallerRouteWithChildren
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/installer/control-room.json': typeof InstallerControlRoomDotjsonRoute
  '/recordings/$recordingId': typeof RecordingsRecordingIdRoute
  '/devices': typeof DevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/installer': typeof InstallerRouteWithChildren
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/installer/control-room.json': typeof InstallerControlRoomDotjsonRoute
  '/recordings/$recordingId': typeof RecordingsRecordingIdRoute
  '/devices/': typeof DevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/installer'
    | '/devices/$deviceId'
    | '/installer/control-room.json'
    | '/recordings/$recordingId'
    | '/devices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/installer'
    | '/devices/$deviceId'
    | '/installer/control-room.json'
    | '/recordings/$recordingId'
    | '/devices'
  id:
    | '__root__'
    | '/'
    | '/installer'
    | '/devices/$deviceId'
    | '/installer/control-room.json'
    | '/recordings/$recordingId'
    | '/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallerRoute: typeof InstallerRouteWithChildren
  RecordingsRecordingIdRoute: typeof RecordingsRecordingIdRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/installer': {
      id: '/installer'
      path: '/installer'
      fullPath: '/installer'
      preLoaderRoute: typeof InstallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/$recordingId': {
      id: '/recordings/$recordingId'
      path: '/recordings/$recordingId'
      fullPath: '/recordings/$recordingId'
      preLoaderRoute: typeof RecordingsRecordingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installer/control-room.json': {
      id: '/installer/control-room.json'
      path: '/control-room.json'
      fullPath: '/installer/control-room.json'
      preLoaderRoute: typeof InstallerControlRoomDotjsonRouteImport
      parentRoute: typeof InstallerRoute
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof DevicesRoute
    }
  }
}

interface InstallerRouteChildren {
  InstallerControlRoomDotjsonRoute: typeof InstallerControlRoomDotjsonRoute
}

const InstallerRouteChildren: InstallerRouteChildren = {
  InstallerControlRoomDotjsonRoute: InstallerControlRoomDotjsonRoute,
}

const InstallerRouteWithChildren = InstallerRoute._addFileChildren(
  InstallerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallerRoute: InstallerRouteWithChildren,
  RecordingsRecordingIdRoute: RecordingsRecordingIdRoute,
  DevicesIndexRoute: DevicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
