{{- if .Values.nats.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sebastian.fullname" . }}-nats
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
    {{- include "sebastian.selectorLabels" (dict "ctx" . "component" "nats") | nindent 4 }}
spec:
  selector:
    {{- include "sebastian.selectorLabels" (dict "ctx" . "component" "nats") | nindent 4 }}
  ports:
    - name: client
      port: 4222
      targetPort: client
    - name: monitor
      port: 8222
      targetPort: monitor
{{- end }}
