//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminSecretScopes  adminSecretContextKey  = "AdminSecret.Scopes"
	DeviceSecretScopes deviceSecretContextKey = "DeviceSecret.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for RecordingKind.
const (
	Agent      RecordingKind = "agent"
	Composite  RecordingKind = "composite"
	Microphone RecordingKind = "microphone"
	Model      RecordingKind = "model"
)

// Valid indicates whether the value is a known member of the RecordingKind enum.
func (e RecordingKind) Valid() bool {
	switch e {
	case Agent:
		return true
	case Composite:
		return true
	case Microphone:
		return true
	case Model:
		return true
	default:
		return false
	}
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Recording defines model for Recording.
type Recording struct {
	ByteSize    int64              `json:"byteSize"`
	CapturedAt  time.Time          `json:"capturedAt"`
	ContentType string             `json:"contentType"`
	CreatedAt   time.Time          `json:"createdAt"`
	DurationMs  int64              `json:"durationMs"`
	FileName    string             `json:"fileName"`
	Id          openapi_types.UUID `json:"id"`
	Kind        RecordingKind      `json:"kind"`
	ObjectUrl   string             `json:"objectUrl"`
	Room        string             `json:"room"`
	SessionId   openapi_types.UUID `json:"sessionId"`
	Transcript  *string            `json:"transcript,omitempty"`
}

// RecordingKind defines model for RecordingKind.
type RecordingKind string

// RecordingList defines model for RecordingList.
type RecordingList struct {
	Items []Recording `json:"items"`
}

// RecordingRegistration defines model for RecordingRegistration.
type RecordingRegistration struct {
	ByteSize    int64         `json:"byteSize"`
	CapturedAt  time.Time     `json:"capturedAt"`
	ContentType string        `json:"contentType"`
	DurationMs  int64         `json:"durationMs"`
	FileName    string        `json:"fileName"`
	Kind        RecordingKind `json:"kind"`
	ObjectUrl   string        `json:"objectUrl"`
	Room        string        `json:"room"`
	Transcript  *string       `json:"transcript,omitempty"`
}

// RecordingSummary defines model for RecordingSummary.
type RecordingSummary struct {
	Count           int64      `json:"count"`
	LastCapturedAt  *time.Time `json:"lastCapturedAt,omitempty"`
	TotalBytes      int64      `json:"totalBytes"`
	TotalDurationMs int64      `json:"totalDurationMs"`
}

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        openapi_types.UUID `json:"id"`
	Room      string             `json:"room"`
	ServerUrl string             `json:"serverUrl"`
	Token     string             `json:"token"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// Unavailable defines model for Unavailable.
type Unavailable = Problem

// adminSecretContextKey is the context key for AdminSecret security scheme
type adminSecretContextKey string

// deviceSecretContextKey is the context key for DeviceSecret security scheme
type deviceSecretContextKey string

// ListRecordingsParams defines parameters for ListRecordings.
type ListRecordingsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateSessionParams defines parameters for CreateSession.
type CreateSessionParams struct {
	XDeviceId     string `json:"X-Device-Id"`
	XDeviceSecret string `json:"X-Device-Secret"`
}

// RegisterRecordingJSONRequestBody defines body for RegisterRecording for application/json ContentType.
type RegisterRecordingJSONRequestBody = RecordingRegistration

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Process liveness
	// (GET /healthz)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// Dependency readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// Firmware-compatible two-line LiveKit connection response
	// (GET /token)
	GetLegacyToken(w http.ResponseWriter, r *http.Request)
	// List recent voice recordings
	// (GET /v1/admin/recordings)
	ListRecordings(w http.ResponseWriter, r *http.Request, params ListRecordingsParams)
	// Register a recording already stored in object storage
	// (POST /v1/admin/recordings)
	RegisterRecording(w http.ResponseWriter, r *http.Request)
	// Aggregate recording storage and duration metrics
	// (GET /v1/admin/recordings/summary)
	GetRecordingsSummary(w http.ResponseWriter, r *http.Request)
	// Get one voice recording
	// (GET /v1/admin/recordings/{recordingId})
	GetRecording(w http.ResponseWriter, r *http.Request, recordingId openapi_types.UUID)
	// Create a device session and dispatch its assigned agent
	// (POST /v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request, params CreateSessionParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLegacyToken operation middleware
func (siw *ServerInterfaceWrapper) GetLegacyToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLegacyToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecordings operation middleware
func (siw *ServerInterfaceWrapper) ListRecordings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecordingsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecordings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterRecording operation middleware
func (siw *ServerInterfaceWrapper) RegisterRecording(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterRecording(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordingsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetRecordingsSummary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordingsSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecording operation middleware
func (siw *ServerInterfaceWrapper) GetRecording(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "recordingId" -------------
	var recordingId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", r.PathValue("recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecording(w, r, recordingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceSecretScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSessionParams

	headers := r.Header

	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Id", Err: err})
			return
		}

		params.XDeviceId = XDeviceId

	} else {
		err := fmt.Errorf("Header parameter X-Device-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Device-Id", Err: err})
		return
	}

	// ------------- Required header parameter "X-Device-Secret" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Secret")]; found {
		var XDeviceSecret string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Secret", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Secret", valueList[0], &XDeviceSecret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Secret", Err: err})
			return
		}

		params.XDeviceSecret = XDeviceSecret

	} else {
		err := fmt.Errorf("Header parameter X-Device-Secret is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Device-Secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/token", wrapper.GetLegacyToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/recordings", wrapper.ListRecordings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/admin/recordings", wrapper.RegisterRecording)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/recordings/summary", wrapper.GetRecordingsSummary)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/recordings/{recordingId}", wrapper.GetRecording)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sessions", wrapper.CreateSession)

	return m
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnavailableApplicationProblemPlusJSONResponse Problem

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse Health

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse Health

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503ApplicationProblemPlusJSONResponse Problem

func (response GetReadiness503ApplicationProblemPlusJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetLegacyTokenRequestObject struct {
}

type GetLegacyTokenResponseObject interface {
	VisitGetLegacyTokenResponse(w http.ResponseWriter) error
}

type GetLegacyToken200TextResponse string

func (response GetLegacyToken200TextResponse) VisitGetLegacyTokenResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetLegacyToken404ApplicationProblemPlusJSONResponse Problem

func (response GetLegacyToken404ApplicationProblemPlusJSONResponse) VisitGetLegacyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetLegacyToken503ApplicationProblemPlusJSONResponse Problem

func (response GetLegacyToken503ApplicationProblemPlusJSONResponse) VisitGetLegacyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListRecordingsRequestObject struct {
	Params ListRecordingsParams
}

type ListRecordingsResponseObject interface {
	VisitListRecordingsResponse(w http.ResponseWriter) error
}

type ListRecordings200JSONResponse RecordingList

func (response ListRecordings200JSONResponse) VisitListRecordingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRecordings401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListRecordings401ApplicationProblemPlusJSONResponse) VisitListRecordingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListRecordings503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response ListRecordings503ApplicationProblemPlusJSONResponse) VisitListRecordingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecordingRequestObject struct {
	Body *RegisterRecordingJSONRequestBody
}

type RegisterRecordingResponseObject interface {
	VisitRegisterRecordingResponse(w http.ResponseWriter) error
}

type RegisterRecording201JSONResponse Recording

func (response RegisterRecording201JSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecording401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RegisterRecording401ApplicationProblemPlusJSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecording404ApplicationProblemPlusJSONResponse Problem

func (response RegisterRecording404ApplicationProblemPlusJSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecording409ApplicationProblemPlusJSONResponse Problem

func (response RegisterRecording409ApplicationProblemPlusJSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecording503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response RegisterRecording503ApplicationProblemPlusJSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecordingsSummaryRequestObject struct {
}

type GetRecordingsSummaryResponseObject interface {
	VisitGetRecordingsSummaryResponse(w http.ResponseWriter) error
}

type GetRecordingsSummary200JSONResponse RecordingSummary

func (response GetRecordingsSummary200JSONResponse) VisitGetRecordingsSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecordingsSummary401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetRecordingsSummary401ApplicationProblemPlusJSONResponse) VisitGetRecordingsSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecordingsSummary503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetRecordingsSummary503ApplicationProblemPlusJSONResponse) VisitGetRecordingsSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecordingRequestObject struct {
	RecordingId openapi_types.UUID `json:"recordingId"`
}

type GetRecordingResponseObject interface {
	VisitGetRecordingResponse(w http.ResponseWriter) error
}

type GetRecording200JSONResponse Recording

func (response GetRecording200JSONResponse) VisitGetRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecording401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetRecording401ApplicationProblemPlusJSONResponse) VisitGetRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecording404ApplicationProblemPlusJSONResponse Problem

func (response GetRecording404ApplicationProblemPlusJSONResponse) VisitGetRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecording503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetRecording503ApplicationProblemPlusJSONResponse) VisitGetRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionRequestObject struct {
	Params CreateSessionParams
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse Session

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession401ApplicationProblemPlusJSONResponse Problem

func (response CreateSession401ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession503ApplicationProblemPlusJSONResponse Problem

func (response CreateSession503ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Process liveness
	// (GET /healthz)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// Dependency readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// Firmware-compatible two-line LiveKit connection response
	// (GET /token)
	GetLegacyToken(ctx context.Context, request GetLegacyTokenRequestObject) (GetLegacyTokenResponseObject, error)
	// List recent voice recordings
	// (GET /v1/admin/recordings)
	ListRecordings(ctx context.Context, request ListRecordingsRequestObject) (ListRecordingsResponseObject, error)
	// Register a recording already stored in object storage
	// (POST /v1/admin/recordings)
	RegisterRecording(ctx context.Context, request RegisterRecordingRequestObject) (RegisterRecordingResponseObject, error)
	// Aggregate recording storage and duration metrics
	// (GET /v1/admin/recordings/summary)
	GetRecordingsSummary(ctx context.Context, request GetRecordingsSummaryRequestObject) (GetRecordingsSummaryResponseObject, error)
	// Get one voice recording
	// (GET /v1/admin/recordings/{recordingId})
	GetRecording(ctx context.Context, request GetRecordingRequestObject) (GetRecordingResponseObject, error)
	// Create a device session and dispatch its assigned agent
	// (POST /v1/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLegacyToken operation middleware
func (sh *strictHandler) GetLegacyToken(w http.ResponseWriter, r *http.Request) {
	var request GetLegacyTokenRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLegacyToken(ctx, request.(GetLegacyTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLegacyToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLegacyTokenResponseObject); ok {
		if err := validResponse.VisitGetLegacyTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRecordings operation middleware
func (sh *strictHandler) ListRecordings(w http.ResponseWriter, r *http.Request, params ListRecordingsParams) {
	var request ListRecordingsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRecordings(ctx, request.(ListRecordingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRecordings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRecordingsResponseObject); ok {
		if err := validResponse.VisitListRecordingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterRecording operation middleware
func (sh *strictHandler) RegisterRecording(w http.ResponseWriter, r *http.Request) {
	var request RegisterRecordingRequestObject

	var body RegisterRecordingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterRecording(ctx, request.(RegisterRecordingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterRecording")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterRecordingResponseObject); ok {
		if err := validResponse.VisitRegisterRecordingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecordingsSummary operation middleware
func (sh *strictHandler) GetRecordingsSummary(w http.ResponseWriter, r *http.Request) {
	var request GetRecordingsSummaryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecordingsSummary(ctx, request.(GetRecordingsSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecordingsSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecordingsSummaryResponseObject); ok {
		if err := validResponse.VisitGetRecordingsSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecording operation middleware
func (sh *strictHandler) GetRecording(w http.ResponseWriter, r *http.Request, recordingId openapi_types.UUID) {
	var request GetRecordingRequestObject

	request.RecordingId = recordingId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecording(ctx, request.(GetRecordingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecording")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecordingResponseObject); ok {
		if err := validResponse.VisitGetRecordingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request, params CreateSessionParams) {
	var request CreateSessionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FlZc9vIEf4rU5O8BSIpH1sx37R2ZaPYSbkku5KqLT0MMU2y18AMdqZBCVbxv6d6cJPgpbVo7xtIzNHH",
	"118feJSxTTNrwJCX00fpwGfWeAg/PhuV09I6/Aqaf8fWEBjiR5VlCcaK0Jpx5uwsgfRvv3lr+J2Pl5Aq",
	"fvqrg7mcyr+M20vG5Vs//ljukuv1OpIafOww4+PkVH5aglA6RYOeXLhDeIgdkEAv0KxUgnok1xELuFKY",
	"qFkC55TvSjj4PUcHWmjIwGgwccGy5a08I8n7qsP4rn+CSmgZZNMa+SSVfHQ2A0fI5p6rxEMks85fj9KT",
	"ojw8gclTOf1V2i/yLpJUZCCn0pNDswg31RLxmmpXu87OfoOY2GK1VqeJoYEUJvy0cXEk0XhSJg72n1uX",
	"KpJTmTu8cDAHB/wm2t7V6pWqB0xZtddv3kSSfR5+XU4mzTY0BAtwvI+QSldvnVj+cbwMGyYLb+vzo30W",
	"vIHYOs1nnGbDWUFwi1/7QqKhn17Jjt6DWscqo9yBvqLeZq0ILgjTQQtXsfCpMsv2eweKTjtS52Uw/ts/",
	"QYc5JvAflQ4Lg7rvuhz1kABf0OhDYdu45z0vXkeV5z67ZBMdQzc4a9NBCT14j9ZcHycoOWVKwhg4bAN5",
	"4YT2+EqGStmO3bqa9N0btdjqOakHnK7H98L6fWXkmnBSqyEJ7o2dzZbW8C1qwTwblcnDI8EAKXXO/ICe",
	"TgwXJEj7D0d5vaUCqZxTxba5w3F7LXADiybx/KmCPEXzAcyCs8zlc8bvgXvOF6YHBDklDJ8n6vbi7DZP",
	"U+WKEyEW29zQExyYKE9vn4AxsqSSnwuCp6AmbH73dNxtOKnUvSfT9h1DNr8t+fVEU8NDhg78KdY6MpPt",
	"yTNuBe7IMCD7BcyRGabCd3t+vT3qqLltuiBSnDuk4pZDtzTMFRfnt6EkDxTNRfESlAYnI2kCS8j/XYRV",
	"F9WylpYzfA8Fi/8OVhjDwWPKZTvPWYcidG7LOrVbpr+1hpxNRJYoA2JunbiFmfKEyggdDvVCGS0+4Are",
	"I4mQ1ESViv2oKQenst139fFaRnIFroSTnIwuR5PAXxkYlaGcypejyeiljGSmaBmsNV6G0v8rPy9KVRll",
	"Aa9cUMhfgFgGA57x3GvBXkwmezqb0zqaqgPZ0XBlzsbgPbcxKsFV3cDUHMWdQ3iftJKSWvjQbxSeIJV3",
	"vGHsQOlir643oDR+X2U5DDAGESsjVBxDRoKcms8xDn3l68nLH7SfbNzxrl3oOvYcdEnDE5VHNGQOYi4G",
	"5ZRcDlsW4rxZkaQAozOLhkbimkSaexIzEPDA5kBKCgGGxdMhkvzS5okWxtaLrActsnyWYJwUHFHbwIeF",
	"iotPFRUdgAPBA42zROGG3Tf5b8vCdYh/vvkg5jZJ7D1oMSsELUH867+fIuEhU44twv8qYeA+QQMBDK8m",
	"r849/OAdinCGCVLReIARodEHc38PmNZGtE5kTICeuLU+gNN/oEvvlYOLWqcEBN3bCzZvw7yxNQbiMOip",
	"EdDBcs8aFaRXl+MwIRq7upryOymHu4+bdhkzs1MpEDg+vso7v+fgijbtJJgiJ5vWaBrmKk9ITl9PonZq",
	"EeYU7dRioIK5e0aS6zdYAy67gZhzWmskYZ0GV8K8qlMF1zIV0i933dioMO4NBVsQHtzUDOq6NUWwf6+a",
	"+PWOLdbihzVj+VmNlWXOdl1X1hjpjwsDkzSr7taRzKwfQEbZ6YFr28eycgJPP1tdfHs/9VrLdb9QYyZe",
	"b4Hl8tsLsQMo5UvhKptUHPMkTHwHylTe2xgDg1cVnNAWfMhF8ICeKm3enFuwspIOmSeUVqE+2rTyMwdR",
	"jXOh2uhpRPFkmRDQ1KLyH2oBR0fXDj4e+7a/3V0K1qvrZvgcbFnftTcOKul/WGK8WiwcLBR1CLH2XKjF",
	"6pGESIEcxv4Pu/Oxeb7W66OcuiPVcmPUZtrOqXKTDrv590BPfZ48ux8y5WcS/6fhzVZyZsm5zc1Z2OgX",
	"IGENbKbzUwFaN+os6nB6fxsm3vXsZxiMO+cNB+CYqodm9Pji79H+UeQ6Onq6cdSNL17/1Lvx5Ytj4uHb",
	"lRK1SQcwVb0S1deGbiycC9bX5RfiasbDkmgwhKqKzB+4a+qGUH86thlDJbSFqpWsa57A/OgzRfFSIHmu",
	"i3BhuD+vPtk0E4I6fO7W62bwWAZG7hI5lWO5vlv/PwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
