//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminSecretScopes  adminSecretContextKey  = "AdminSecret.Scopes"
	DeviceSecretScopes deviceSecretContextKey = "DeviceSecret.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for RecordingKind.
const (
	Agent      RecordingKind = "agent"
	Composite  RecordingKind = "composite"
	Microphone RecordingKind = "microphone"
	Model      RecordingKind = "model"
)

// Valid indicates whether the value is a known member of the RecordingKind enum.
func (e RecordingKind) Valid() bool {
	switch e {
	case Agent:
		return true
	case Composite:
		return true
	case Microphone:
		return true
	case Model:
		return true
	default:
		return false
	}
}

// DesiredProfile defines model for DesiredProfile.
type DesiredProfile struct {
	// Name Firmware profile name. Empty or absent clears the desired state.
	Name *string `json:"name,omitempty"`
}

// Device defines model for Device.
type Device struct {
	DesiredProfile    *string    `json:"desiredProfile,omitempty"`
	DisplayName       string     `json:"displayName"`
	Enabled           bool       `json:"enabled"`
	Id                string     `json:"id"`
	ProfileReportedAt *time.Time `json:"profileReportedAt,omitempty"`
	ReportedProfile   *string    `json:"reportedProfile,omitempty"`
}

// DeviceList defines model for DeviceList.
type DeviceList struct {
	Items []Device `json:"items"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Recording defines model for Recording.
type Recording struct {
	ByteSize    int64              `json:"byteSize"`
	CapturedAt  time.Time          `json:"capturedAt"`
	ContentType string             `json:"contentType"`
	CreatedAt   time.Time          `json:"createdAt"`
	DurationMs  int64              `json:"durationMs"`
	FileName    string             `json:"fileName"`
	Id          openapi_types.UUID `json:"id"`
	Kind        RecordingKind      `json:"kind"`
	ObjectUrl   string             `json:"objectUrl"`
	Room        string             `json:"room"`
	SessionId   openapi_types.UUID `json:"sessionId"`
	Transcript  *string            `json:"transcript,omitempty"`
}

// RecordingKind defines model for RecordingKind.
type RecordingKind string

// RecordingList defines model for RecordingList.
type RecordingList struct {
	Items []Recording `json:"items"`
}

// RecordingRegistration defines model for RecordingRegistration.
type RecordingRegistration struct {
	ByteSize    int64         `json:"byteSize"`
	CapturedAt  time.Time     `json:"capturedAt"`
	ContentType string        `json:"contentType"`
	DurationMs  int64         `json:"durationMs"`
	FileName    string        `json:"fileName"`
	Kind        RecordingKind `json:"kind"`
	ObjectUrl   string        `json:"objectUrl"`
	Room        string        `json:"room"`
	Transcript  *string       `json:"transcript,omitempty"`
}

// RecordingSummary defines model for RecordingSummary.
type RecordingSummary struct {
	Count           int64      `json:"count"`
	LastCapturedAt  *time.Time `json:"lastCapturedAt,omitempty"`
	TotalBytes      int64      `json:"totalBytes"`
	TotalDurationMs int64      `json:"totalDurationMs"`
}

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        openapi_types.UUID `json:"id"`
	Room      string             `json:"room"`
	ServerUrl string             `json:"serverUrl"`
	Token     string             `json:"token"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// Unavailable defines model for Unavailable.
type Unavailable = Problem

// adminSecretContextKey is the context key for AdminSecret security scheme
type adminSecretContextKey string

// deviceSecretContextKey is the context key for DeviceSecret security scheme
type deviceSecretContextKey string

// ListRecordingsParams defines parameters for ListRecordings.
type ListRecordingsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetDesiredProfileParams defines parameters for GetDesiredProfile.
type GetDesiredProfileParams struct {
	Current *string `form:"current,omitempty" json:"current,omitempty"`
}

// CreateSessionParams defines parameters for CreateSession.
type CreateSessionParams struct {
	XDeviceId     string `json:"X-Device-Id"`
	XDeviceSecret string `json:"X-Device-Secret"`
}

// SetDesiredProfileJSONRequestBody defines body for SetDesiredProfile for application/json ContentType.
type SetDesiredProfileJSONRequestBody = DesiredProfile

// RegisterRecordingJSONRequestBody defines body for RegisterRecording for application/json ContentType.
type RegisterRecordingJSONRequestBody = RecordingRegistration

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Process liveness
	// (GET /healthz)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// Dependency readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// Firmware-compatible two-line LiveKit connection response
	// (GET /token)
	GetLegacyToken(w http.ResponseWriter, r *http.Request)
	// List known devices with profile state
	// (GET /v1/admin/devices)
	ListDevices(w http.ResponseWriter, r *http.Request)
	// Set (or clear) the desired device profile
	// (PUT /v1/admin/devices/{deviceId}/desired-profile)
	SetDesiredProfile(w http.ResponseWriter, r *http.Request, deviceId string)
	// List recent voice recordings
	// (GET /v1/admin/recordings)
	ListRecordings(w http.ResponseWriter, r *http.Request, params ListRecordingsParams)
	// Register a recording already stored in object storage
	// (POST /v1/admin/recordings)
	RegisterRecording(w http.ResponseWriter, r *http.Request)
	// Aggregate recording storage and duration metrics
	// (GET /v1/admin/recordings/summary)
	GetRecordingsSummary(w http.ResponseWriter, r *http.Request)
	// Get one voice recording
	// (GET /v1/admin/recordings/{recordingId})
	GetRecording(w http.ResponseWriter, r *http.Request, recordingId openapi_types.UUID)
	// Desired device profile for reconciliation polls
	// (GET /v1/devices/{deviceId}/desired-profile)
	GetDesiredProfile(w http.ResponseWriter, r *http.Request, deviceId string, params GetDesiredProfileParams)
	// Create a device session and dispatch its assigned agent
	// (POST /v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request, params CreateSessionParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLegacyToken operation middleware
func (siw *ServerInterfaceWrapper) GetLegacyToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLegacyToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetDesiredProfile operation middleware
func (siw *ServerInterfaceWrapper) SetDesiredProfile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId string

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", r.PathValue("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetDesiredProfile(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecordings operation middleware
func (siw *ServerInterfaceWrapper) ListRecordings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecordingsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecordings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterRecording operation middleware
func (siw *ServerInterfaceWrapper) RegisterRecording(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterRecording(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordingsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetRecordingsSummary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordingsSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecording operation middleware
func (siw *ServerInterfaceWrapper) GetRecording(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "recordingId" -------------
	var recordingId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", r.PathValue("recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecording(w, r, recordingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDesiredProfile operation middleware
func (siw *ServerInterfaceWrapper) GetDesiredProfile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId string

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", r.PathValue("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDesiredProfileParams

	// ------------- Optional query parameter "current" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "current", r.URL.Query(), &params.Current, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "current"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "current", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDesiredProfile(w, r, deviceId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceSecretScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSessionParams

	headers := r.Header

	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Id", Err: err})
			return
		}

		params.XDeviceId = XDeviceId

	} else {
		err := fmt.Errorf("Header parameter X-Device-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Device-Id", Err: err})
		return
	}

	// ------------- Required header parameter "X-Device-Secret" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Secret")]; found {
		var XDeviceSecret string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Secret", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Secret", valueList[0], &XDeviceSecret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Secret", Err: err})
			return
		}

		params.XDeviceSecret = XDeviceSecret

	} else {
		err := fmt.Errorf("Header parameter X-Device-Secret is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Device-Secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/token", wrapper.GetLegacyToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/devices", wrapper.ListDevices)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/admin/devices/{deviceId}/desired-profile", wrapper.SetDesiredProfile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/recordings", wrapper.ListRecordings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/admin/recordings", wrapper.RegisterRecording)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/recordings/summary", wrapper.GetRecordingsSummary)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/recordings/{recordingId}", wrapper.GetRecording)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/devices/{deviceId}/desired-profile", wrapper.GetDesiredProfile)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sessions", wrapper.CreateSession)

	return m
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnavailableApplicationProblemPlusJSONResponse Problem

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse Health

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse Health

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503ApplicationProblemPlusJSONResponse Problem

func (response GetReadiness503ApplicationProblemPlusJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetLegacyTokenRequestObject struct {
}

type GetLegacyTokenResponseObject interface {
	VisitGetLegacyTokenResponse(w http.ResponseWriter) error
}

type GetLegacyToken200TextResponse string

func (response GetLegacyToken200TextResponse) VisitGetLegacyTokenResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetLegacyToken404ApplicationProblemPlusJSONResponse Problem

func (response GetLegacyToken404ApplicationProblemPlusJSONResponse) VisitGetLegacyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetLegacyToken503ApplicationProblemPlusJSONResponse Problem

func (response GetLegacyToken503ApplicationProblemPlusJSONResponse) VisitGetLegacyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListDevicesRequestObject struct {
}

type ListDevicesResponseObject interface {
	VisitListDevicesResponse(w http.ResponseWriter) error
}

type ListDevices200JSONResponse DeviceList

func (response ListDevices200JSONResponse) VisitListDevicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDevices401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListDevices401ApplicationProblemPlusJSONResponse) VisitListDevicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDevices503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response ListDevices503ApplicationProblemPlusJSONResponse) VisitListDevicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SetDesiredProfileRequestObject struct {
	DeviceId string `json:"deviceId"`
	Body     *SetDesiredProfileJSONRequestBody
}

type SetDesiredProfileResponseObject interface {
	VisitSetDesiredProfileResponse(w http.ResponseWriter) error
}

type SetDesiredProfile204Response struct {
}

func (response SetDesiredProfile204Response) VisitSetDesiredProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetDesiredProfile401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response SetDesiredProfile401ApplicationProblemPlusJSONResponse) VisitSetDesiredProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetDesiredProfile404ApplicationProblemPlusJSONResponse Problem

func (response SetDesiredProfile404ApplicationProblemPlusJSONResponse) VisitSetDesiredProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SetDesiredProfile503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response SetDesiredProfile503ApplicationProblemPlusJSONResponse) VisitSetDesiredProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListRecordingsRequestObject struct {
	Params ListRecordingsParams
}

type ListRecordingsResponseObject interface {
	VisitListRecordingsResponse(w http.ResponseWriter) error
}

type ListRecordings200JSONResponse RecordingList

func (response ListRecordings200JSONResponse) VisitListRecordingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRecordings401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListRecordings401ApplicationProblemPlusJSONResponse) VisitListRecordingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListRecordings503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response ListRecordings503ApplicationProblemPlusJSONResponse) VisitListRecordingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecordingRequestObject struct {
	Body *RegisterRecordingJSONRequestBody
}

type RegisterRecordingResponseObject interface {
	VisitRegisterRecordingResponse(w http.ResponseWriter) error
}

type RegisterRecording201JSONResponse Recording

func (response RegisterRecording201JSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecording401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RegisterRecording401ApplicationProblemPlusJSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecording404ApplicationProblemPlusJSONResponse Problem

func (response RegisterRecording404ApplicationProblemPlusJSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecording409ApplicationProblemPlusJSONResponse Problem

func (response RegisterRecording409ApplicationProblemPlusJSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRecording503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response RegisterRecording503ApplicationProblemPlusJSONResponse) VisitRegisterRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecordingsSummaryRequestObject struct {
}

type GetRecordingsSummaryResponseObject interface {
	VisitGetRecordingsSummaryResponse(w http.ResponseWriter) error
}

type GetRecordingsSummary200JSONResponse RecordingSummary

func (response GetRecordingsSummary200JSONResponse) VisitGetRecordingsSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecordingsSummary401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetRecordingsSummary401ApplicationProblemPlusJSONResponse) VisitGetRecordingsSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecordingsSummary503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetRecordingsSummary503ApplicationProblemPlusJSONResponse) VisitGetRecordingsSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecordingRequestObject struct {
	RecordingId openapi_types.UUID `json:"recordingId"`
}

type GetRecordingResponseObject interface {
	VisitGetRecordingResponse(w http.ResponseWriter) error
}

type GetRecording200JSONResponse Recording

func (response GetRecording200JSONResponse) VisitGetRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecording401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetRecording401ApplicationProblemPlusJSONResponse) VisitGetRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecording404ApplicationProblemPlusJSONResponse Problem

func (response GetRecording404ApplicationProblemPlusJSONResponse) VisitGetRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecording503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetRecording503ApplicationProblemPlusJSONResponse) VisitGetRecordingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetDesiredProfileRequestObject struct {
	DeviceId string `json:"deviceId"`
	Params   GetDesiredProfileParams
}

type GetDesiredProfileResponseObject interface {
	VisitGetDesiredProfileResponse(w http.ResponseWriter) error
}

type GetDesiredProfile200TextResponse string

func (response GetDesiredProfile200TextResponse) VisitGetDesiredProfileResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetDesiredProfile503ApplicationProblemPlusJSONResponse Problem

func (response GetDesiredProfile503ApplicationProblemPlusJSONResponse) VisitGetDesiredProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionRequestObject struct {
	Params CreateSessionParams
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse Session

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession401ApplicationProblemPlusJSONResponse Problem

func (response CreateSession401ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession503ApplicationProblemPlusJSONResponse Problem

func (response CreateSession503ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Process liveness
	// (GET /healthz)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// Dependency readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// Firmware-compatible two-line LiveKit connection response
	// (GET /token)
	GetLegacyToken(ctx context.Context, request GetLegacyTokenRequestObject) (GetLegacyTokenResponseObject, error)
	// List known devices with profile state
	// (GET /v1/admin/devices)
	ListDevices(ctx context.Context, request ListDevicesRequestObject) (ListDevicesResponseObject, error)
	// Set (or clear) the desired device profile
	// (PUT /v1/admin/devices/{deviceId}/desired-profile)
	SetDesiredProfile(ctx context.Context, request SetDesiredProfileRequestObject) (SetDesiredProfileResponseObject, error)
	// List recent voice recordings
	// (GET /v1/admin/recordings)
	ListRecordings(ctx context.Context, request ListRecordingsRequestObject) (ListRecordingsResponseObject, error)
	// Register a recording already stored in object storage
	// (POST /v1/admin/recordings)
	RegisterRecording(ctx context.Context, request RegisterRecordingRequestObject) (RegisterRecordingResponseObject, error)
	// Aggregate recording storage and duration metrics
	// (GET /v1/admin/recordings/summary)
	GetRecordingsSummary(ctx context.Context, request GetRecordingsSummaryRequestObject) (GetRecordingsSummaryResponseObject, error)
	// Get one voice recording
	// (GET /v1/admin/recordings/{recordingId})
	GetRecording(ctx context.Context, request GetRecordingRequestObject) (GetRecordingResponseObject, error)
	// Desired device profile for reconciliation polls
	// (GET /v1/devices/{deviceId}/desired-profile)
	GetDesiredProfile(ctx context.Context, request GetDesiredProfileRequestObject) (GetDesiredProfileResponseObject, error)
	// Create a device session and dispatch its assigned agent
	// (POST /v1/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLegacyToken operation middleware
func (sh *strictHandler) GetLegacyToken(w http.ResponseWriter, r *http.Request) {
	var request GetLegacyTokenRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLegacyToken(ctx, request.(GetLegacyTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLegacyToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLegacyTokenResponseObject); ok {
		if err := validResponse.VisitGetLegacyTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDevices operation middleware
func (sh *strictHandler) ListDevices(w http.ResponseWriter, r *http.Request) {
	var request ListDevicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDevices(ctx, request.(ListDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDevicesResponseObject); ok {
		if err := validResponse.VisitListDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetDesiredProfile operation middleware
func (sh *strictHandler) SetDesiredProfile(w http.ResponseWriter, r *http.Request, deviceId string) {
	var request SetDesiredProfileRequestObject

	request.DeviceId = deviceId

	var body SetDesiredProfileJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetDesiredProfile(ctx, request.(SetDesiredProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetDesiredProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetDesiredProfileResponseObject); ok {
		if err := validResponse.VisitSetDesiredProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRecordings operation middleware
func (sh *strictHandler) ListRecordings(w http.ResponseWriter, r *http.Request, params ListRecordingsParams) {
	var request ListRecordingsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRecordings(ctx, request.(ListRecordingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRecordings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRecordingsResponseObject); ok {
		if err := validResponse.VisitListRecordingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterRecording operation middleware
func (sh *strictHandler) RegisterRecording(w http.ResponseWriter, r *http.Request) {
	var request RegisterRecordingRequestObject

	var body RegisterRecordingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterRecording(ctx, request.(RegisterRecordingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterRecording")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterRecordingResponseObject); ok {
		if err := validResponse.VisitRegisterRecordingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecordingsSummary operation middleware
func (sh *strictHandler) GetRecordingsSummary(w http.ResponseWriter, r *http.Request) {
	var request GetRecordingsSummaryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecordingsSummary(ctx, request.(GetRecordingsSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecordingsSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecordingsSummaryResponseObject); ok {
		if err := validResponse.VisitGetRecordingsSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecording operation middleware
func (sh *strictHandler) GetRecording(w http.ResponseWriter, r *http.Request, recordingId openapi_types.UUID) {
	var request GetRecordingRequestObject

	request.RecordingId = recordingId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecording(ctx, request.(GetRecordingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecording")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecordingResponseObject); ok {
		if err := validResponse.VisitGetRecordingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDesiredProfile operation middleware
func (sh *strictHandler) GetDesiredProfile(w http.ResponseWriter, r *http.Request, deviceId string, params GetDesiredProfileParams) {
	var request GetDesiredProfileRequestObject

	request.DeviceId = deviceId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDesiredProfile(ctx, request.(GetDesiredProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDesiredProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDesiredProfileResponseObject); ok {
		if err := validResponse.VisitGetDesiredProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request, params CreateSessionParams) {
	var request CreateSessionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Frrbxu5Ef9XCLYf7tC1JOdxaHSfcnF7dZMWgZ2gBQIDRy1HEi9cco+clb0J9L8Xw+W+pJUsuZGTfFtp",
	"+RjO/Ob1437mqc1ya8Cg59PP3IHPrfEQfrw3osCldeoTSPqdWoNgkB5FnmuVClTWjHNnZxqyv/zuraF3",
	"Pl1CJujpzw7mfMr/NG43GVdv/fhtNYuv1+uES/CpUzktx6f83RKYkJkyyqMLezAPqQNkyjNlVkIrOeLr",
	"hARcCaXFTMNjyveSOfijUA4kk5CDkWDSkmQrWnlGnObFxWivC/A0462zc1WJK6RUtKLQb53NwaEitc+F",
	"9pDwvPPXZ25EFqb05fi7ctmtcMDyalFGw0bsb1mOJbOOiZkHgyzVIJxnuAQmKyGYR4Ew4gnPxN0bMAtc",
	"8ulPTxOOZQ58yj06ZRbhBPEfO/sdUiSdX8BKpcfKL7cOv7FTwqXyuRblv+NJt96DIbXKzruZtRqEoZdK",
	"Ds6JermC3DoE+TJAY25dJpBPuRQIZ6gy4Mn2VBfn7BY5DKpgwKcfSIT+IVqRb3aq8Y3yeKQqFULWf9iH",
	"4mit1pDCOVFuCx/WGpLzHyA0oeMoGQleRXgCU2S0gf3YWX2HBuOsISlqZzwWdSiUHkSGMh6FqXDcAKJw",
	"6szBHBzQmwFQtOfKxJ3K6GjPX7xIOIWq8Ot8MmmmKYOwABd0r3AH6qs/DpdhQ2Xhbb1+sk+DV5BaJ2mN",
	"43Q4KxGu1ae+kMrgT89459yDp05FjoU7zu1iCH8X1bL93oE40pNlUeWQf/kHnIF8f2dIqqJOa7oixICt",
	"YR+Vkff5aWOe1zR4nUTLvXd6Ex2DwcrabFBCD94ray4PExSdMFV+OTDctctHGeJhO3rrnqRv3qTFVs9I",
	"PeB0Lb4X1q+jkuuAk1kJOpg3dTZfWkO7iAWVB0lV83iFMBCUOmuePDq3TvnwAN2scQWLpl76rpw8U6au",
	"Qc5P6b/37PN4bnqPIMe44Wm8bi/OrossE648EmKpLQw+wIBaeHz1AIyhRaF/KREegpow+eLhuNswUnX2",
	"nkzbewzp/LqKr0eqGu5y5cAfo60DM9mePONW4A50A7QfwRyYYSK+2/Xr6UnnmNuqCyKlhVNYXpPrVop5",
	"ST3ldegkQ4imHmoJQoLjSWyx+H/PwqizOKwNy7l6DWVbud+7TDVs5zrrUITO7XZX98oadFazXAsDbG4d",
	"u4aZ8KiEYTIs6pkwkr1RK3itkIWkxmIq9qOmHJzydt7Lt5c84StwFZz4ZHQ+moT4lYMRueJT/nQ0GT3l",
	"Cc8FLoO2xstQ+n+i50V1VEJZwCsVFPxXQJLBgCc895iDJ5PJnob8uEY8diA7eILc2RS8p+5baLWq++46",
	"RlHnEN7rVlIUCx/6jdIjZPyGJowdCFnuPesVCKm+7mHJDVQKLBWGiTSFHBk6MZ+rNNAhzydPv1EapDHH",
	"RTvQdfQ5aJImTkSLSMgdpFQM8im6ArY0RHkzBkkGRuZWGRyxS2RZ4ZHNgMEdqUOhLlnszYMn+aUttGTG",
	"1oOsB8nyYqZVqkvyqG3gw0Kk5bsYiu6BA8IdjnMt1IbeN+PfloZrF39/9YbNrdb2FiSblYHK+ed/3iXM",
	"Qy4caYT+FczArVYGAhieTZ49NmdHMwSqmdIKy8YChAipfFD314BprUTrWE4B0CO11vfgtKbWzuozaWB4",
	"a89IvU3kTa0xkAZ+skZAB8s9bURIr87Hgdgcx0C+M95Q63ERx5ww3HRYqAHNRQGYdRJchbFIvD6bnO9a",
	"upF13KOPW7vfO6mhdLtpnE8/bCTwDzfrm67J6BTso7G3bZq8VbhsyNHAeXbs02eYqRqO+h421fhz9XAp",
	"1+NIZ57lLTmYFwNWvAbcoH0pvzqRAYLz4UiheqCc29YO9T68Ww9VAa+1aoe4PX/y12R/T0GKoqXA4y9W",
	"ll8QPr3DrfslHIm83gLvs+2KJy7TsZR1IH+OjHXIeEFG8Iz82DCFnhm4Q5ZbrR8OyEcOkZU7hTQzt4Xp",
	"BcNTOcU1IPvBuuoO4MfeHUDUbN4g81jHcHVHuD+MXbXDhtH/RwGubOGvVaaoYG71LWEuCo18+nyStMxr",
	"4Fpb5nWgC7s5YeTsk0QD1r6ClOryVkndMBp7bUb92LcdUF11jJUlrLiuKXfCpTPqZp3w3PoBZFRsFbiW",
	"AjtNiBqmxw6KVOdfXogdQKleMhd1AvK7iWnhqtZ7m6pQhcYulEkLPgQ6uFMe42lePLZgFRsQqufQHoYe",
	"b1PLJ3aiGudMtN7TiFIlOqZMLSr9IRZwsHftiMdj33J0u9vZenRN6D1GtKz32usHUfpvNjC+XCwcLAR2",
	"AmJtudBP1rQqywCdSv3/bc7PzfOlXB9k1IMKzc6qe2vNe3jBx8mz+yFTXfX67yZutpI/ajn4K1D9DJvp",
	"/FiAHtYSNbTNdhF8NhepMosRozA9bz5jsVp7hkvlG/IgYdWHGKQpqvpdYQw9163CSgn2W1o4BwZ/S4L3",
	"UcWiVtD/4KX7hQz7AcIXMjMrS3a7BMMM6UR55gF/HLH3pt9FkmiiQHvWZg7mLTNwywpDQok8B+EojGP9",
	"5RJTZgUGrSupX5kr5wNdgCLFEbsmIQLNVIRT+1ALCs8qymvKPgLkodWZz8OSFRXFqLJ1BpAVBpWuC/jU",
	"gQSDSmjPtCAcDfBV30YbmgxX/NF+fMfCQx8m3ZyOdLsYgMzPrILMJlq+Bp/19mAS62Kw0wtXCuTVJlVa",
	"VYkqeF4nCmx1fPX1QqA6Bgv6V+Gevr6xGgbYzluSk6Ds/juZg3Z88vyn3o5PnxwCxy/XPNQqHYBCfMXi",
	"NxLd7PdYaLysPsccCEbfOtfbTZr9O73NrFlBm4n6kHWXE2o95XOB6TJkJ+G9WhiQrP7QpLnXqN3nZr1u",
	"rksrxyic5lM+5uub9f8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
