{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sebastian.fullname" . }}-server
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
    {{- include "sebastian.selectorLabels" (dict "ctx" . "component" "server") | nindent 4 }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "sebastian.selectorLabels" (dict "ctx" . "component" "server") | nindent 4 }}
{{- end }}
