/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a device session and dispatch its assigned agent
         * @description With `kind=meeting` the agent is dispatched in meeting mode for that meeting (design 14 §3.2).
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{deviceId}/desired-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Desired device profile for reconciliation polls
         * @description Device-facing. The firmware polls this endpoint, reporting its running profile via `current`, and receives the desired profile name (empty body when none is set). Unknown devices are auto-registered so new units appear in the admin inventory on first contact.
         */
        get: operations["getDesiredProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{deviceId}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The desired sebastian.config.v1 document for this device
         * @description Device-facing, authenticated with the per-device secret. Returned only when the control room holds a desired config; the document carries `configVersion` so the device echoes it in its next poll.
         */
        get: operations["getDeviceConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{deviceId}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Challenge for a device to enrol with the organization secret
         * @description Device-facing, first step of the enrolment (RF-03/RF-51): a unit provisioned from the embedded installer holds the organization secret but no device secret yet, so it asks this control room for one. The nonce is single-use and expires after 60 s. 404 when this control room has no organization secret (enrolment is not possible).
         */
        get: operations["getEnrollmentChallenge"];
        put?: never;
        /**
         * Enrol a device that proves it holds the organization secret
         * @description Second step: `mac` = hex HMAC-SHA256(organization secret, nonce + "." + deviceId), the same construction the LAN adoption uses, and the unit's own device secret (born with the unit). On success the control room adopts the unit and keeps the secret's digest for `POST /v1/sessions`.
         */
        post: operations["enrollDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{deviceId}/running-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * The device reports the configuration it runs (RF-42)
         * @description Device-facing, authenticated with the device secret. Sent at boot (every applied change reboots), without secrets or the WiFi password. The ficha shows it as the "running" column and seeds its form from it.
         */
        put: operations["reportRunningConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/control-room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This control room's identity and provisioning defaults
         * @description What the embedded installer pre-fills and what adoption writes into a device. The organization secret is included: this endpoint is behind the administration secret and must only be called server-side.
         */
        get: operations["getControlRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The fleet view — known devices joined with what mDNS sees on the LAN */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One device with its desired config and recent sessions */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a device */
        patch: operations["updateDevice"];
        trace?: never;
    };
    "/v1/admin/devices/{deviceId}/adopt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adopt a device over the network (discovered, or by IP)
         * @description Starts an adoption job: hello/nonce, then the control room's config signed with the organization secret (or the device secret supplied in the body). The job reports progress (waiting for the MUTE button on a factory unit, queued behind a conversation) and, once adopted, the per-device secret — shown once.
         */
        post: operations["adoptDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/devices/{deviceId}/forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return a device to factory (unadopted) and drop it from the inventory */
        post: operations["forgetDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/adoptions/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress of an adoption or forget job */
        get: operations["getAdoptionJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/devices/{deviceId}/desired-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the desired sebastian.config.v1 for a device
         * @description Stored with a version; the device picks it up on its next poll, stores it and restarts. WiFi changes are applied by the device as a trial with automatic rollback.
         */
        put: operations["setDesiredConfig"];
        post?: never;
        /** Clear the desired config */
        delete: operations["clearDesiredConfig"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/devices/{deviceId}/secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a new per-device secret (shown once)
         * @description The new secret reaches the device inside its next desired config; the old one keeps working until the device first authenticates with the new one.
         */
        post: operations["regenerateDeviceSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/devices/{deviceId}/desired-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set (or clear) the desired device profile */
        put: operations["setDesiredProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/devices/{deviceId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the unit to record a meeting (RM-03)
         * @description Creates a meeting in state `requested` and sends the unit the order over the LAN, signed with the organization secret; the unit's next poll carries it too (RM-06). One meeting per unit (RM-05); only in the agente profile (RM-44).
         */
        post: operations["startMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meetings, newest first (RM-40) */
        get: operations["listMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/meetings/{meetingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One meeting (RM-41) */
        get: operations["getMeeting"];
        put?: never;
        post?: never;
        /** Delete audio and content irreversibly, keeping the trace (RM-46) */
        delete: operations["deleteMeeting"];
        options?: never;
        head?: never;
        /** Rename speakers and flag the meeting to keep (RM-31, RM-45) */
        patch: operations["updateMeeting"];
        trace?: never;
    };
    "/v1/admin/meetings/{meetingId}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The transcript as a download, txt or srt (RM-41) */
        get: operations["getMeetingTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/meetings/{meetingId}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe again (RM-33) */
        post: operations["transcribeMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/meetings/{meetingId}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate the summary again (RM-32) */
        post: operations["summarizeMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/meetings/{meetingId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a meeting (RM-22; the agent uses it for RM-21) */
        post: operations["stopMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{deviceId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The unit asks for a meeting after the MUTE gesture (RM-02) */
        post: operations["requestMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{deviceId}/meeting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** The unit confirms it records, or that it stopped and why (RM-52) */
        put: operations["reportMeeting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent voice recordings */
        get: operations["listRecordings"];
        put?: never;
        /** Register a recording already stored in object storage */
        post: operations["registerRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/recordings/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate recording storage and duration metrics */
        get: operations["getRecordingsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/recordings/{recordingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one voice recording */
        get: operations["getRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Session: {
            /** Format: uuid */
            id: string;
            room: string;
            /** Format: uri */
            serverUrl: string;
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
        /** @enum {string} */
        RecordingKind: "model" | "microphone" | "agent" | "composite";
        Recording: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            room: string;
            kind: components["schemas"]["RecordingKind"];
            fileName: string;
            /** Format: uri */
            objectUrl: string;
            contentType: string;
            /** Format: int64 */
            byteSize: number;
            /** Format: int64 */
            durationMs: number;
            /** Format: date-time */
            capturedAt: string;
            /** Format: date-time */
            createdAt: string;
            transcript?: string;
        };
        RecordingRegistration: {
            room: string;
            kind: components["schemas"]["RecordingKind"];
            fileName: string;
            /** Format: uri */
            objectUrl: string;
            contentType: string;
            /** Format: int64 */
            byteSize: number;
            /** Format: int64 */
            durationMs: number;
            /** Format: date-time */
            capturedAt: string;
            transcript?: string;
        };
        RecordingList: {
            items: components["schemas"]["Recording"][];
        };
        /**
         * @description adopted = bound here and polling; joining = adopted here, waiting for its first contact since the adoption (it is rebooting; up to 3 min); absent = bound here, silent for more than three poll periods and not on the LAN; moved = adopted here but the LAN announces it bound to another control room after its last contact with us (someone took it); leaving = forgotten here, the LAN still carries its old announce; managed_elsewhere = seen on the LAN, bound to another control room; unadopted = seen on the LAN, bound to none; orphan = seen on the LAN, bound to a control room it cannot reach; registered = polled this control room without being adopted (legacy /token units).
         * @enum {string}
         */
        DeviceState: "adopted" | "joining" | "absent" | "moved" | "leaving" | "managed_elsewhere" | "unadopted" | "orphan" | "registered";
        Device: {
            id: string;
            displayName: string;
            enabled: boolean;
            state: components["schemas"]["DeviceState"];
            /** Format: date-time */
            adoptedAt?: string;
            desiredProfile?: string;
            reportedProfile?: string;
            /** Format: date-time */
            profileReportedAt?: string;
            firmware?: string;
            ip?: string;
            /** @description Origin the device announces it is bound to (may be another control room). */
            controlRoom?: string;
            /** @description What the device reports about its last control-room contact (empty = ok). */
            lastError?: string;
            /** @description The unit's last event worth telling the owner (RF-36/42): adopt-denied:<ip>, cfg-rejected:<why>, or the error of its previous boot. Kept until the unit reports another. */
            lastEvent?: string;
            /**
             * Format: date-time
             * @description When this control room first saw lastEvent.
             */
            lastEventAt?: string;
            reportedConfigVersion?: string;
            desiredConfigVersion?: string;
            /** Format: date-time */
            seenOnLanAt?: string;
            /** @description Minutes without voice that end a meeting recording (RM-23). */
            meetingSilenceMin?: number;
            /** @description Maximum length of a meeting recording (RM-24). */
            meetingMaxHours?: number;
        };
        DeviceDetail: components["schemas"]["Device"] & {
            hasDeviceSecret: boolean;
            runningConfig?: components["schemas"]["DeviceConfig"];
            /** Format: date-time */
            runningConfigAt?: string;
            desiredConfig?: components["schemas"]["DeviceConfig"];
            sessions: components["schemas"]["DeviceSession"][];
        };
        DeviceSession: {
            /** Format: uuid */
            id: string;
            room: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: int64 */
            recordingCount: number;
        };
        DeviceUpdate: {
            displayName?: string;
            /** @description Minutes without voice that end a meeting recording (RM-23). */
            meetingSilenceMin?: number;
            /** @description A recording never exceeds this (RM-24). */
            meetingMaxHours?: number;
        };
        /** @description A sebastian.config.v1 document (see web-installer/public/PROVISIONING.md). Validated by the firmware. */
        DeviceConfig: {
            [key: string]: unknown;
        };
        DesiredConfigVersion: {
            version: string;
        };
        DeviceSecret: {
            deviceSecret: string;
        };
        ControlRoom: {
            name: string;
            /** @description The URL devices use to reach this control room (token server). */
            apiUrl: string;
            syslogIp?: string;
            syslogPort?: number;
            discoveryEnabled: boolean;
            adoptPort: number;
            orgSecretConfigured: boolean;
            /** @description Present only for server-side callers; never ship to a browser. */
            orgSecret?: string;
        };
        AdoptionRequest: {
            /** @description Address of the device when it was not discovered (adopt by IP). */
            ip?: string;
            /** @description Sign with this device secret instead of the organization secret (handover of a single unit). */
            deviceSecret?: string;
            config?: components["schemas"]["DeviceConfig"];
        };
        /** @enum {string} */
        AdoptionPhase: "starting" | "waiting_consent" | "queued" | "adopted" | "forgotten" | "failed";
        AdoptionJob: {
            /** Format: uuid */
            id: string;
            deviceId: string;
            /** @enum {string} */
            kind: "adopt" | "forget";
            ip?: string;
            phase: components["schemas"]["AdoptionPhase"];
            /** @description Why it failed — auth, nonce, no_reply, consent_timeout, wifi, json… */
            error?: string;
            /** @description The per-device secret issued by this adoption. Shown once; the job expires. */
            deviceSecret?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DeviceList: {
            items: components["schemas"]["Device"][];
        };
        EnrollmentChallenge: {
            nonce: string;
        };
        EnrollmentRequest: {
            nonce: string;
            /** @description hex HMAC-SHA256(organization secret, nonce + "." + deviceId) */
            mac: string;
            /** @description The unit's own secret, which this control room will authenticate its sessions with. */
            deviceSecret: string;
        };
        EnrollmentResponse: {
            /** @description Name of the control room that adopted the unit. */
            controlRoom: string;
        };
        DesiredProfile: {
            /** @description Firmware profile name. Empty or absent clears the desired state. */
            name?: string;
        };
        /**
         * @description requested = asked, the unit has not confirmed; recording; closing = stop asked, file being closed; transcribing; ready; no_transcript = audio only, retryable; cut = the unit vanished, audio kept up to that point.
         * @enum {string}
         */
        MeetingState: "requested" | "recording" | "closing" | "transcribing" | "ready" | "no_transcript" | "cut";
        Meeting: {
            /** Format: uuid */
            id: string;
            deviceId: string;
            state: components["schemas"]["MeetingState"];
            /** @enum {string} */
            requestedBy: "gesture" | "dashboard" | "voice";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            /** @enum {string} */
            endReason?: "gesture" | "dashboard" | "voice" | "silence" | "max_duration" | "device_lost" | "room_lost";
            /**
             * Format: int64
             * @description Recorded duration; while recording, the live duration so far (RM-14).
             */
            durationMs: number;
            /** Format: int64 */
            audioBytes: number;
            hasAudio: boolean;
            /** @description Excluded from retention (RM-45). */
            keep: boolean;
            /** Format: date-time */
            deletedAt?: string;
            transcript?: components["schemas"]["MeetingTranscript"];
            /** @description Why the transcription failed (RM-33), with state no_transcript. */
            transcriptError?: string;
            summary?: components["schemas"]["MeetingSummary"];
        };
        MeetingTranscript: {
            /** @description ISO-639-1, when known. */
            language?: string;
            /** @description The whole transcript, one "Speaker: text" line per segment. */
            text: string;
            segments: components["schemas"]["MeetingSegment"][];
            /** @description Names the operator gave to speaker ids (RM-31). */
            speakers?: {
                [key: string]: string;
            };
            model?: string;
            /** @description False when the fallback model transcribed without speakers. */
            diarized: boolean;
        };
        MeetingSegment: {
            /**
             * Format: double
             * @description Seconds from the start of the recording.
             */
            start: number;
            /** Format: double */
            end: number;
            /** @description Speaker id ("Hablante 1"); empty without diarization. */
            speaker: string;
            text: string;
        };
        MeetingSummary: {
            language?: string;
            text: string;
            agreements: string[];
            actions: string[];
            /** @description Generated automatically by this model (RM-32). */
            model: string;
            /** Format: date-time */
            generatedAt: string;
        };
        MeetingPatch: {
            /** @description Speaker id → name; an empty name removes the alias (RM-31). */
            speakers?: {
                [key: string]: string;
            };
            /** @description Exclude from retention (RM-45). */
            keep?: boolean;
        };
        MeetingList: {
            items: components["schemas"]["Meeting"][];
        };
        MeetingStart: {
            /**
             * @default dashboard
             * @enum {string}
             */
            requestedBy: "gesture" | "dashboard" | "voice";
        };
        MeetingStop: {
            /**
             * @default dashboard
             * @enum {string}
             */
            reason: "dashboard" | "voice" | "silence";
        };
        MeetingReport: {
            /** Format: uuid */
            meetingId: string;
            /** @enum {string} */
            state: "recording" | "stopped";
            /**
             * @description Why the unit stopped (only with `stopped`).
             * @enum {string}
             */
            reason?: "gesture" | "room_lost";
        };
        SessionRequest: {
            /**
             * @default conversation
             * @enum {string}
             */
            kind: "conversation" | "meeting";
            /** Format: uuid */
            meetingId?: string;
        };
        RecordingSummary: {
            /** Format: int64 */
            count: number;
            /** Format: int64 */
            totalBytes: number;
            /** Format: int64 */
            totalDurationMs: number;
            /** Format: date-time */
            lastCapturedAt?: string;
        };
    };
    responses: {
        /** @description The meeting does not exist. */
        MeetingNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Device not found. */
        DeviceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The administration secret is invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A required dependency is unavailable. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        DeviceId: string;
        MeetingId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service can accept traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description A required dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
                "X-Device-Secret": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Invalid device credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description LiveKit or persistence is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDesiredProfile: {
        parameters: {
            query?: {
                current?: string;
                /** @description Version of the config the device is running (empty = none). */
                cfg?: string;
                /** @description Firmware version the device is running. */
                fw?: string;
                /** @description The unit's last event worth telling the owner (RF-36/42): adopt-denied:<ip>, cfg-rejected:<why>, or the error recorded by its previous boot. Empty when none. */
                ev?: string;
            };
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desired profile name; empty when none is set. */
            200: {
                headers: {
                    /** @description Version of the desired config; the device fetches it when different from `cfg`. */
                    "X-Desired-Config"?: string;
                    /** @description A pending meeting order (RM-06): start:<meetingId> or stop:<meetingId>. Absent when none. */
                    "X-Meeting"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Persistence is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDeviceConfig: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Secret": string;
            };
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The desired config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceConfig"];
                };
            };
            /** @description Invalid device credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No desired config for this device. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getEnrollmentChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The challenge. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentChallenge"];
                };
            };
            /** @description Enrolment is not available on this control room. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    enrollDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description Enrolled: this control room holds the unit's secret now. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description The nonce is unknown, expired or the proof does not match. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Enrolment is not available on this control room. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    reportRunningConfig: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Secret": string;
            };
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceConfig"];
            };
        };
        responses: {
            /** @description Recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid device credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getControlRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control room settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlRoom"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices ordered by id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DeviceNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DeviceNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    adoptDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdoptionRequest"];
            };
        };
        responses: {
            /** @description Adoption started. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoptionJob"];
                };
            };
            /** @description No address for the device (not seen on the LAN and no `ip` given). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    forgetDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdoptionRequest"];
            };
        };
        responses: {
            /** @description Forget started (the device is told over the network, then removed). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoptionJob"];
                };
            };
            /** @description No address for the device. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DeviceNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    getAdoptionJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoptionJob"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Unknown or expired job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setDesiredConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceConfig"];
            };
        };
        responses: {
            /** @description Stored; returns the assigned version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesiredConfigVersion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DeviceNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    clearDesiredConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DeviceNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    regenerateDeviceSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new secret. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSecret"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DeviceNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    setDesiredProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesiredProfile"];
            };
        };
        responses: {
            /** @description Desired profile stored; the device applies it on its next poll. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Device not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    startMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MeetingStart"];
            };
        };
        responses: {
            /** @description Meeting requested. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DeviceNotFound"];
            /** @description A meeting is already in progress on this unit (RM-05). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The unit cannot record (not adopted here, or not in the agente profile). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    listMeetings: {
        parameters: {
            query?: {
                deviceId?: string;
                state?: components["schemas"]["MeetingState"];
                /** @description Text to find in the transcript or the summary (RM-42). */
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meetings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The meeting. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["MeetingNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["MeetingNotFound"];
            /** @description The meeting is still in progress. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    updateMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingPatch"];
            };
        };
        responses: {
            /** @description The meeting as updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["MeetingNotFound"];
            /** @description There is no transcript whose speakers could be renamed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getMeetingTranscript: {
        parameters: {
            query?: {
                format?: "txt" | "srt";
            };
            header?: never;
            path: {
                meetingId: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["MeetingNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    transcribeMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["MeetingNotFound"];
            /** @description The meeting is in progress, already transcribing, or has no audio. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    summarizeMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["MeetingNotFound"];
            /** @description There is no transcript to summarize. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    stopMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MeetingStop"];
            };
        };
        responses: {
            /** @description Stopping. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["MeetingNotFound"];
            /** @description The meeting is not in progress. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    requestMeeting: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Secret": string;
            };
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting requested; the unit starts it with this id. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description A meeting is already in progress on this unit (RM-05). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The unit cannot record (not adopted here, not contacting, or not in the agente profile). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    reportMeeting: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Secret": string;
            };
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingReport"];
            };
        };
        responses: {
            /** @description Recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["MeetingNotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    listRecordings: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent recordings ordered by capture time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    registerRecording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordingRegistration"];
            };
        };
        responses: {
            /** @description Recording registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The associated session does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The object URL is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getRecordingsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recording summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recording details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Recording not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
}
